"turn off vi compatibility
set nocompatible

let &runtimepath = &runtimepath . ',' . finddir('bundle/pathogen', &runtimepath)
call pathogen#infect()

"syntax highlighting on
syntax on

"Background color/style
set background=dark

"Setting the default colorscheme
colorscheme solarized

"buffers can now exist in background
set hidden

"turn on plugins and stuff
filetype on
filetype plugin on
filetype indent on

set backspace=indent,eol,start

let g:ctrlp_map = '`'
let g:ctrlp_working_path_mode = '0'
let g:ctrlp_custom_ignore = 'node_modules\|dist/\|jspm_packages'

" Map jj to esc in insert mode. Esc is too far away.
inoremap jj <Esc>

"Some command remaps to not have to pay attention
cnoreabbrev W w
cnoreabbrev Wa wa
cnoreabbrev WA wa
cnoreabbrev Q q
cnoreabbrev Qa qa
cnoreabbrev QA qa

" set list lcs=tab:>-,trail:>
set list lcs=tab:\|\ ,trail:<

"binds to make HL behave like a stronger h and l
nnoremap <silent> H ^
nnoremap <silent> L $
vnoremap <silent> H ^
vnoremap <silent> L $

set pastetoggle=<leader>k

"Obviousmode
set laststatus=2

"turn on line numbers
set number

"turn on line and column markers
set cursorline
set cursorcolumn

"automatic and smart indent
set autoindent
set noexpandtab
set copyindent
set smartindent
set tabstop=4
set shiftwidth=4

"search related settings
set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
set scrolloff=8

"turn off useless clutter files
set noswapfile
set nobackup
set nowb

"Fast scrolling
set ttyfast
set lazyredraw

"Persistent undo
set undodir=~/.vim/undodir
set undofile
set undolevels=1000 "maximum number of changes that can be undone
set undoreload=10000 "maximum number lines to save for undo on a buffer reload

"Code folding
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

"Syntastic settings
let g:syntastic_check_on_wq = 0
let g:syntastic_aggregate_errors = 1
let g:syntastic_auto_jump = 1
let g:syntastic_mode_map = { 'mode': 'passive' }
let g:syntastic_cpp_compiler_options = ' -std=gnu++0x'
let g:syntastic_php_checkers=['php', 'phpmd']
let g:syntastic_ruby_checkers=['rubocop']

map <Leader>s :SyntasticToggleMode<CR>

"Powerline settings
let g:Powerline_symbols = "fancy"

"Neocomplete
let g:neocomplete#enable_at_startup = 1

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3

autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

set rtp+=$HOME/dotfiles/powerline/powerline/bindings/vim/

" Always show statusline
set laststatus=2

" " Use 256 colours (Use this setting only if your terminal supports 256
" colours)
set t_Co=256

" Set binding for sudo save
cmap w!! w !sudo tee > /dev/null %

" indentation lines
let g:indentLine_setColors = 0
let g:indentLine_char = '|'

" remap keys for yankstack
nmap <leader>p <Plug>yankstack_substitute_older_paste
nmap <leader>P <Plug>yankstack_substitute_newer_paste

let g:gitgutter_realtime = 1
let g:gitgutter_eager = 1
set updatetime=100
